image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - init: yarn install
    command: yarn dev
vscode:
  extensions:
    - octref.vetur@0.26.1:NrU4ZTLY6IF/1G6B/QLuIQ==
